#!/usr/bin/env node
const { program } = require('commander');
const initCommands = require('./src/commands/index.js');

async function main() {
    initCommands(program).forEach(command => command.setUp());

    await program.parseAsync(process.argv);
}

main();
