# This is a basic workflow to help you get started with Actions

name: Test & Deploy to Github Pages @ master

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      VITE_APP_BASE_URL: ${{ secrets.VITE_APP_BASE_URL }}
      VITE_APP_BASE_TITLE: ${{ secrets.VITE_APP_BASE_TITLE }}
      VITE_GOOGLE_ANALYTICS_MEASUREMENT_ID: ${{ secrets.VITE_GOOGLE_ANALYTICS_MEASUREMENT_ID }}
      VITE_TWITTER_USER: ${{ secrets.VITE_TWITTER_USER }}
      VITE_TINY_LETTER_USER: ${{ secrets.VITE_TINY_LETTER_USER }}
      VITE_DISQUS_USER: ${{ secrets.VITE_DISQUS_USER }}
      VITE_PROJECT_GITHUB_URL: ${{ secrets.VITE_PROJECT_GITHUB_URL }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Show branch
        run: echo ${{ github.ref }}

      - name: Apt installs
        run: |
          sudo apt update
          sudo apt install tree

      - name: Creates .env file
        run: |
          touch .env
          echo VITE_APP_BASE_URL="${{ secrets.VITE_APP_BASE_URL }}" >> .env
          echo VITE_APP_BASE_TITLE="${{ secrets.VITE_APP_BASE_TITLE }}" >> .env
          echo VITE_GOOGLE_ANALYTICS_MEASUREMENT_ID="${{ secrets.VITE_GOOGLE_ANALYTICS_MEASUREMENT_ID }}" >> .env
          echo VITE_TWITTER_USER="${{ secrets.VITE_TWITTER_USER }}" >> .env
          echo VITE_TINY_LETTER_USER="${{ secrets.VITE_TINY_LETTER_USER }}" >> .env
          echo VITE_DISQUS_USER="${{ secrets.VITE_DISQUS_USER }}" >> .env
          echo VITE_PROJECT_GITHUB_URL="${{ secrets.VITE_PROJECT_GITHUB_URL }}" >> .env

      - name: Cypress test in docker image
        run: |
          yarn docker:cypress:build
          yarn docker:cypress:run

      - name: Docker build for export
        run: yarn docker:build

      - name: Removes .env file
        run: rm .env

      - name: Copies build from docker image
        run: |
          id=$(docker create angelblanco.dev:latest)
          docker cp $id:/home/node/app/dist ./dist
          docker rm -v $id

      - name: Inspect dist folder
        run: tree dist

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.0.0
        if: github.ref == 'refs/heads/master'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
